/**
 * Ready-made mob library — one click loads a complete mob with colors and a
 * walk animation, so nothing has to be built from scratch.
 *
 * Contains the REAL vanilla Minecraft mob models (geometry + textures +
 * walk animations, generated by tools/generate-vanilla.js from
 * assets/vanilla) plus one plain humanoid template for custom work.
 */
import { VANILLA_MOBS } from './vanilla.js';
import { DEEP_VOID_MOBS } from './deepvoid.js';
import { VOXEL_MOBS } from './voxel.js';

/** Pack every cube without an explicit UV offset into the texture (shelf packer). */
function autoLayoutUVs(model) {
    let texW = model.textureWidth || 128;
    let texH = model.textureHeight || 128;

    for (let attempt = 0; attempt < 4; attempt++) {
        let y = 0, rowH = 0, x = 0, overflow = false;
        for (const bone of model.bones) {
            for (const cube of bone.cubes) {
                if (cube.uv && Array.isArray(cube.uv.offset)) continue;
                const [w, h, d] = cube.size;
                const extW = 2 * d + 2 * w;
                const extH = d + h;
                if (x + extW > texW) {
                    x = 0;
                    y += rowH;
                    rowH = 0;
                }
                if (y + extH > texH) { overflow = true; break; }
                cube.uv = cube.uv || {};
                cube.uv.offset = [x, y];
                x += extW;
                rowH = Math.max(rowH, extH);
            }
            if (overflow) break;
        }
        if (!overflow) break;
        texW *= 2;
        texH *= 2;
    }
    model.textureWidth = texW;
    model.textureHeight = texH;
}

function walkCycle(legs, arms, length = 40, swing = 22) {
    const tracks = {};
    const q = length / 4;
    // Jalat ja kädet eteen–taakse (X-akseli) — oikea kävely, ei sivuttainen heilunta
    legs.forEach((name, i) => {
        const p = (i % 2 === 0) ? 1 : -1;
        tracks[name] = {
            0: [p * swing, 0, 0],
            [Math.round(q)]: [-p * swing, 0, 0],
            [Math.round(q * 2)]: [p * swing, 0, 0],
            [Math.round(q * 3)]: [-p * swing, 0, 0]
        };
    });
    arms.forEach((name, i) => {
        const p = -((i % 2 === 0) ? 1 : -1);
        tracks[name] = {
            0: [p * swing * 0.7, 0, 0],
            [Math.round(q)]: [-p * swing * 0.7, 0, 0],
            [Math.round(q * 2)]: [p * swing * 0.7, 0, 0],
            [Math.round(q * 3)]: [-p * swing * 0.7, 0, 0]
        };
    });
    return { length, tracks };
}

function cube(name, origin, size, color) {
    return { name, origin, size, rotation: [0, 0, 0], color, uv: {}, mirror: false };
}
function bone(name, pivot, cubes) {
    return { name, pivot, rotation: [0, 0, 0], cubes };
}

// A plain humanoid template with bright colors for custom work
const HUMANOID = {
    name: 'Humanoid',
    emoji: '🧍',
    description: 'Plain humanoid template with bright colors — good starting point',
    model: {
        modelId: 'geometry.humanoid',
        textureWidth: 128, textureHeight: 128,
        bones: [
            bone('root', [0, 0, 0], [cube('body', [0, 12, 0], [8, 12, 4], '#3fb950')]),
            bone('head', [0, 24, 0], [cube('head', [0, 24, 0], [8, 8, 8], '#d29922')]),
            bone('left_arm', [-5, 23, 0], [cube('left_arm', [-5, 12, 0], [4, 12, 4], '#58a6ff')]),
            bone('right_arm', [5, 23, 0], [cube('right_arm', [5, 12, 0], [4, 12, 4], '#58a6ff')]),
            bone('left_leg', [-2, 12, 0], [cube('left_leg', [-2, 0, 0], [4, 12, 4], '#f85149')]),
            bone('right_leg', [2, 12, 0], [cube('right_leg', [2, 0, 0], [4, 12, 4], '#f85149')])
        ]
    },
    animation: walkCycle(['left_leg', 'right_leg'], ['left_arm', 'right_arm'], 40, 25)
};

export const LIBRARY_MOBS = [
    ...VANILLA_MOBS.map(m => ({ ...m, category: 'vanilla' })),
    { ...HUMANOID, category: 'template' },
    ...DEEP_VOID_MOBS.map(m => ({ ...m, category: 'deepvoid' })),
    ...VOXEL_MOBS.map(m => ({ ...m, category: 'voxel' }))
];

/**
 * Mobi korkeus LOHKOINA rest-asennosta (luut vanhempiensa sisällä,
 * ei animaatiota). Vanilja/16px-mitat jaetaan 16:lla; Deep Void -mobit
 * ovat jo lohkoasteikolla (×0.1) — muuten vertailu olisi pielessä.
 */
function mobHeightBlocks(model, category) {
    const byName = new Map(model.bones.map(b => [b.name, b]));
    const world = new Map();
    function worldPivot(bone) {
        if (world.has(bone.name)) return world.get(bone.name);
        const parent = bone.parent ? byName.get(bone.parent) : null;
        const p = parent ? worldPivot(parent) : [0, 0, 0];
        const w = [
            p[0] + bone.pivot[0] - (parent ? parent.pivot[0] : 0),
            p[1] + bone.pivot[1] - (parent ? parent.pivot[1] : 0),
            p[2] + bone.pivot[2] - (parent ? parent.pivot[2] : 0)
        ];
        world.set(bone.name, w);
        return w;
    }
    let minY = Infinity, maxY = -Infinity;
    for (const bone of model.bones) {
        const wp = worldPivot(bone);
        for (const c of bone.cubes) {
            for (let i = 0; i < 8; i++) {
                const y = wp[1] + (c.origin[1] - bone.pivot[1]) + (i & 2 ? c.size[1] : 0);
                if (y < minY) minY = y;
                if (y > maxY) maxY = y;
            }
        }
    }
    if (!isFinite(minY) || !isFinite(maxY)) return 0;
    const scale = category === 'deepvoid' ? 1 : 1 / 16;
    return Math.round((maxY - minY) * scale * 100) / 100;
}

/**
 * Täydennä yksi mobi kirjastovalmiiksi: UV-pakkaus + korkeus lohkoina +
 * bossi/minioni-tier + kokoluokka. Käytetään sekä moduulin latauksessa
 * että selaimessa vokseloiduille omille malleille (drag & drop).
 */
export function prepareMob(mob) {
    autoLayoutUVs(mob.model);
    mob.size = mobHeightBlocks(mob.model, mob.category || 'voxel');
    const bones = mob.model.bones.length;
    const cubes = mob.model.bones.reduce((n, b) => n + b.cubes.length, 0);
    if (mob.category === 'voxel') {
        // Voxel-mobit: kuutiomäärä on vokselointiartefakti (ei rakenne) —
        // tier päätetään korkeudesta: ≥ 3 lohkoa = bossi (Voxel Dragon)
        mob.score = Math.round(mob.size * 10) / 10;
        mob.tier = mob.size >= 3 ? 'boss' : 'minion';
    } else {
        mob.score = Math.round((mob.size + bones * 0.35 + cubes * 0.12) * 10) / 10;
        mob.tier = mob.score >= 16 ? 'boss' : 'minion';
    }
    // Kokoluokka lohkoina: <1.5 Pieni, 1.5–4 Keskikoko, 4–8.5 Iso, ≥8.5 Jättiläinen
    if (mob.size < 1.5) mob.sizeClass = 'pieni';
    else if (mob.size < 4) mob.sizeClass = 'keski';
    else if (mob.size < 8.5) mob.sizeClass = 'iso';
    else mob.sizeClass = 'jatti';
    return mob;
}

// Pre-pack UVs once so every library mob is colored correctly on load
for (const mob of LIBRARY_MOBS) prepareMob(mob);
