/**
 * Java Edition model format exporter.
 * Generates a Minecraft Java Edition model JSON with elements, per-face
 * textures/UVs, single-axis rotations and a display section suitable for
 * use in mods and resource packs.
 */
import { computeFaceRects, FACE_ORDER } from '../utils/boxuv.js';

const JAVA_FACE = {
    east: 'east', west: 'west', up: 'up', down: 'down', south: 'south', north: 'north'
};

export function exportJavaModel(model, textureName) {
    const texRef = textureName || model.modelId.replace('geometry.', '');
    const elements = [];
    let elementIndex = 0;

    for (const bone of model.bones) {
        for (const cube of bone.cubes) {
            // Java elements are positioned in 0-16 model space. We flatten the
            // bone hierarchy: element from/to = cube extent in world space,
            // mapped so the model's ground (y=0) sits at 8 (middle of 0-16).
            const wx = cube.origin[0];
            const wy = cube.origin[1];
            const wz = cube.origin[2];
            const half = cube.size.map(s => s / 2);

            const from = [wx - half[0] + 8, wy - half[1], wz - half[2] + 8];
            const to = [wx + half[0] + 8, wy + half[1], wz + half[2] + 8];

            const element = {
                name: `${bone.name}_${cube.name || elementIndex}`,
                from: from.map(v => Math.round(v * 100) / 100),
                to: to.map(v => Math.round(v * 100) / 100),
                faces: {}
            };

            // Single-axis rotation (Java limitation)
            const rot = addRotation(element, cube, bone);
            if (rot) element.rotation = rot;

            // Faces with UVs in 0-16 texture space
            const rects = computeFaceRects(cube);
            for (const r of rects) {
                const jf = JAVA_FACE[r.face];
                if (!jf) continue;
                element.faces[jf] = {
                    uv: [
                        Math.round(r.x / model.textureWidth * 16 * 100) / 100,
                        Math.round(r.y / model.textureHeight * 16 * 100) / 100,
                        Math.round((r.x + r.w) / model.textureWidth * 16 * 100) / 100,
                        Math.round((r.y + r.h) / model.textureHeight * 16 * 100) / 100
                    ],
                    texture: `#${cube.name || 'layer0'}`
                };
            }

            elements.push(element);
            elementIndex++;
        }
    }

    // Texture keys: layer0 + one per cube name (deduped)
    const textures = {
        particle: `freebuff:item/${texRef}`,
        layer0: `freebuff:item/${texRef}`
    };
    for (const el of elements) {
        const key = el.name.split('_').pop();
        textures[key] = textures[key] || `freebuff:item/${texRef}`;
    }

    return {
        parent: 'item/generated',
        textures,
        elements,
        display: defaultDisplay(),
        comment: `Generated by Freebuff Mob Studio - ${new Date().toISOString()}`
    };
}

/** Java allows rotation about a single axis only. */
function addRotation(element, cube, bone) {
    const rot = cube.rotation || [0, 0, 0];
    const axes = ['x', 'y', 'z'];
    let axis = null, angle = 0;
    for (let i = 0; i < 3; i++) {
        if (Math.abs(rot[i]) > 0.01) {
            axis = axes[i];
            angle = rot[i];
            break;
        }
    }
    if (!axis) return null;

    return {
        origin: [
            Math.round((cube.origin[0] + 8) * 100) / 100,
            Math.round(cube.origin[1] * 100) / 100,
            Math.round((cube.origin[2] + 8) * 100) / 100
        ],
        axis,
        angle: Math.round(angle * 100) / 100,
        rescale: false
    };
}

function defaultDisplay() {
    return {
        head: {
            rotation: [30, 225, 0],
            translation: [0, 0, 0],
            scale: [0.625, 0.625, 0.625]
        },
        ground: {
            rotation: [0, 0, 0],
            translation: [0, 3, 0],
            scale: [0.25, 0.25, 0.25]
        },
        thirdperson_righthand: {
            rotation: [75, 45, 0],
            translation: [0, 2.5, 0],
            scale: [0.375, 0.375, 0.375]
        }
    };
}
